services:


  db:
    image: postgres:16-alpine
    restart: on-failure
#    env_file:
#      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - :"5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER"]
#      interval: 10s
#      retries: 5
#      timeout: 5s
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  app:
    build: .
    image: mg0rby/habits:${{ github.sha }}  # Укажите имя образа с вашим именем пользователя
    tty: true
    ports:
      - 8000:8000
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  redis:
    image: redis:latest
    restart: on-failure
  celery:
    build: .
    tty: true
    command: sh -c "celery -A config worker -l INFO & celery -A config beat -l INFO"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
      - db
#  celery-beat:
#    build: .
#    tty: true
#    command: sh -c "celery -A config beat -l INFO"
#    restart: on-failure
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#      - app
#      - db


volumes:
  pg_data:


