# Generated by Django 5.1.4 on 2024-12-18 04:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="frequency_type",
            field=models.CharField(
                blank=True,
                choices=[("DAILY", "Ежедневно"), ("WEEKLY", "По дням недели")],
                default="DAILY",
                max_length=10,
                null=True,
                verbose_name="Тип периодичности",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="weekdays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[
                        (1, "Понедельник"),
                        (2, "Вторник"),
                        (3, "Среда"),
                        (4, "Четверг"),
                        (5, "Пятница"),
                        (6, "Суббота"),
                        (7, "Воскресенье"),
                    ]
                ),
                blank=True,
                help_text="Если выбрано 'По дням недели', укажите дни выполнения",
                null=True,
                size=None,
                verbose_name="Дни недели",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=1,
                help_text="Периодичность выполнения привычки для напоминания в днях",
                null=True,
                verbose_name="Периодичность",
            ),
        ),
    ]
