name: Django CI

on: [push]
jobs: #Начало секции джобов
  print_hello: #Название джоба
    runs-on: ubuntu-latest #Среда выполнения джоба

    steps: #Начало секции шагов
      - name: Print hello #Название шага
        run: echo "Hello world!" #Команда, которая будет выполнена в терминале

#jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      env:
        SECRET_KEY : 3b85o3eg0&(dl_6kz2!21b@snsr5(p#r721nj!ypf-pe4$4$$p
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test