name: Django CI

on: [ push ]
jobs: #Начало секции джобов
  print_hello: #Название джоба
    runs-on: ubuntu-latest #Среда выполнения джоба

    steps: #Начало секции шагов
      - name: Print hello #Название шага
        run: echo "Hello world!" #Команда, которая будет выполнена в терминале

  #jobs:

#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.12'
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8
#
#      - name: Run Flake8
#        run: flake8 .
#
  install:


    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16-alpine
        # Provide the password for postgres
        env:

          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST : localhost
          POSTGRES_PORT : 5432

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
	  - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |

          pip install -r requirements.txt

      - name: Run migrations
        env:
          SECRET_KEY : 3b85o3eg0&(dl_6kz2!21b@snsr5(p#r721nj!ypf-pe4$4$$p

        run: python manage.py migrate